POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "duynghiadev",
  "password": "123456"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "duynghia",
  "password": "123456"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhYTIwOWZkZjhlYjQxMWM0NzJlODUiLCJpYXQiOjE3MTkzMTI5MDZ9.e9x5I68bk-5t8OunYwb2Uy2NH3REVTHs_EE5NZmtkaQ

{
  "title": "React",
  "description": "React",
  "url": "react.com",
  "status": "LEARNING"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhODVmYzliMjlmNDE1NjRhYTFhNmUiLCJpYXQiOjE3MTkzMTM1NzZ9.bEpy0yPJ7Goteu7oLswsvT5N_PyTXceih7oXfalntAI

###

PUT http://localhost:5000/api/posts/667aa1965920383e18cc20b1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhODVmYzliMjlmNDE1NjRhYTFhNmUiLCJpYXQiOjE3MTkzMTM1NzZ9.bEpy0yPJ7Goteu7oLswsvT5N_PyTXceih7oXfalntAI

{
  "title": "React",
  "description": "React is perfect",
  "url": "Vue.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/667aa1965920383e18cc20b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhODVmYzliMjlmNDE1NjRhYTFhNmUiLCJpYXQiOjE3MTkzMTM1NzZ9.bEpy0yPJ7Goteu7oLswsvT5N_PyTXceih7oXfalntAI

